### ISSUE TITLE
Duplicate key error - null key

### ISSUE THREAD

**Issue by alexandre** [zakird/celerybeat-mongo#11]
Hi guys, look at this error:
```
beat raised exception <class 'mongoengine.errors.NotUniqueError'>: NotUniqueError('Tried to save duplicate unique keys (insertDocument :: caused by :: 11000 E11000 duplicate key error index: heroku_app25944079.schedules.$name_1  dup key: { : null })',)
```
Situation:

Everytime that I restart celerybeat,  a document with an empty name is created. Even when I delete it. It has just the "total_run" and "last_run_at" attributes.

Sometimes I'm trying save a new task in the database and I get a duplicate unique keys error. I'm certain that my tasks do not have duplicate names:

``` python
# how I create my tasks name
periodic_task = celerybeatmongo.models.PeriodicTask(
        name='verify_tml_delay_{}'.format(datetime.datetime.now().isoformat()),
        ....
```

The weirdest thing is the document with empty data... perhaps it is related to the duplicate names?

Any guidance or suggestion will be of extreme value: i have been stuck with this for hours! 

Many thanks in advance!

Cheers,

**Comment by alexandre** [comment]
up!

@zakird some idea?

**Comment by zakird** [comment]
Task name must be unique according to the database model. It looks like the name is getting set to NULL in your code (i'm not sure why your format isn't working, but that doesn't seem to be related celerybeat-mongo). When you insert your second NULL it fails on the unique constraint.

**Comment by alexandre** [comment]
@zakird ,

I'm sorry man, but that's "Captain Obvious" answer. I'm my text, I said:

__Sometimes I'm trying save a new task in the database and I get a duplicate unique keys error. I'm certain that my tasks do not have duplicate names__

Is possible the celerybeat-mongo creates a null named task?

Thanks for your effort.

P.S IMHO, it's really weird you close a issue based on an idea that is not from the OP.

**Comment by zakird** [comment]
So there isn't _any_ code in celerybeat-mongo that touches name. The
library simply provides a mongoengine model. I closed the issue because
it's not based on the code in this library.

Either this is an issue with your format statement, or you are creating the
mongoengine document incorrectly. The error clearly states that the
duplicate value is the NULL value. You need to look at why the mongoengine
model you created is getting a NULL value. Unless mongoengine or mongodb is
broken, you ARE creating tasks with duplicate names. One thing that jumps
out immediately is I don't know why you are passing names into the
constructor of the document. I don't know whether this is supported

**Comment by zakird** [comment]
If there is a bug with the celerybeat-mongo library itself, I'm happy to
reopen the ticket.

**Comment by GelaniNijraj** [comment]
I'm facing a similar issue. Do you, by any chance, remember how you got around this issue, @alexandre?
